[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/services/lead-capture"
  to = "/services/lead-capture/"
  status = 301

[[redirects]]
  from = "/internal"
  to = "/internal/"
  status = 301

[[redirects]]
  from = "/projects/*"
  to = "/projects/index.html"
  status = 200
